global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8091"]
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: "service"
        replacement: "user-service"

  - job_name: "course-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["course-service:8092"]
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: "service"
        replacement: "course-service"

  - job_name: "test-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["test-service:8093"]
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: "service"
        replacement: "test-service"

  - job_name: "submission-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["submission-service:8094"]
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: "service"
        replacement: "submission-service"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]