apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  labels:
    app: course-service
spec:
  replicas: 1 # Начальное количество реплик
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: maga-diplom-course-service:latest
          imagePullPolicy: Never # Для локальных образов в Minikube
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/maga-diplom
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SERVICES_USER_SERVICE_URL
              value: http://user-service:8091
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "600Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 120
            periodSeconds: 30
# ---
# Horizontal Pod Autoscaler для демонстрации автомасштабирования
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: course-service-hpa
#   labels:
#     app: course-service
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: course-service
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70 # Масштабирование при 70% CPU
