apiVersion: v1
kind: Service
metadata:
  name: submission-service
  labels:
    app: submission-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8094"
spec:
  selector:
    app: submission-service
  ports:
    - port: 8094
      targetPort: 8094
      name: http
  type: NodePort # Используем NodePort для доступа извне Minikube
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: submission-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: submission-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
