apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service
  # annotations:
  #   prometheus.io/path: "/actuator/prometheus"
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "8093"
spec:
  selector:
    app: test-service
  ports:
    - port: 8093
      targetPort: 8093
      name: http
  type: NodePort # Используем NodePort для доступа извне Minikube
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: test-service-monitor
#   namespace: default
#   labels:
#     release: prometheus
# spec:
#   selector:
#     matchLabels:
#       app: test-service
#   endpoints:
#   - port: http
#     path: /actuator/prometheus
#     interval: 15s
#   namespaceSelector:
#     matchNames:
#     - default
