apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  replicas: 1 # Начальное количество реплик
  selector:
    matchLabels:
      app: test-service
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
        - name: test-service
          image: maga-diplom-test-service:latest
          imagePullPolicy: Never # Для локальных образов в Minikube
          ports:
            - containerPort: 8093
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/maga-diplom
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SERVICES_USER_SERVICE_URL
              value: http://user-service:8091
            - name: SERVICES_COURSE_SERVICE_URL
              value: http://course-service:8092
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "600Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8093
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8093
            initialDelaySeconds: 120
            periodSeconds: 30
# ---
# Horizontal Pod Autoscaler для демонстрации автомасштабирования
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: test-service-hpa
#   labels:
#     app: test-service
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: test-service
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70 # Масштабирование при 70% CPU
