apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8091"
spec:
  selector:
    app: user-service
  ports:
    - port: 8091
      targetPort: 8091
      name: http
  type: NodePort # Используем NodePort для доступа извне Minikube
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default