server:
  port: 8091

spring:
  application:
    name: user-service
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/maga-diplom}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 часа
      refresh-token:
        expiration: 604800000 # 7 дней

services:
  course-service:
    url: http://course-service:8092
  test-service:
    url: http://test-service:8093
  submission-service:
    url: http://submission-service:8094

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus, metrics" # добавил metrics для более полного сбора
    endpoint:
      health:
        show-details: always
    metrics:
      tags:
        application: ${spring.application.name} # группировка метрик по сервису
    distribution:
      percentiles-histogram:
        http.server.requests: true # включает гистограммы для времени ответа
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms # SLA для времени ответа
  prometheus:
    metrics:
      export:
        enabled: true